name: Download Takeout

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download file
        run: |
          curl -L "https://takeout.google.com/takeout/download?j=8ebe3836-7b53-4e23-b77c-6c2c7935d850&i=0&user=115269325274265252941&rapt=AEjHL4MHyDHGodSoJ6lKMOJR0ksPbCj4y4CD7TobBqD2wNRzMNbU6Q602wVy7Vneom9xuJbWXgRK6xMio6ogxFz07pomfO-h7enIBHrljYiZ8XBbCX58TUQ" -o takeout.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: takeout.zip
